const fs = require('fs');
let code = fs.readFileSync('appscript_v5.js', 'utf8');

const newDocsTodos = `const DOCS_TODOS = [
  "CARATULA DE DOCUMENTOS", "FACTURA ORIGINAL", "FACTURA COPIA O CARTA COMPROMISO O REFACTURA", 
  "TENENCIA 2019", "TENENCIA 2020", "TENENCIA 2021", "TENENCIA 2022", "TENENCIA 2023", 
  "TENENCIA 2024", "TENENCIA 2025", "TENENCIA 2026", "TENENCIA 2027", 
  "BAJA DE PLACAS O CARTA COMPROMISO", "TARJETA DE CIRCULACION", "VERIFICACION", 
  "VALUACION DE LA UNIDAD", "PRESUPUESTO DE REPARACION", "GUIA AZUL", "INE DEL CLIENTE", 
  "COMP DE DOMICILIO", "CURP", "CSF", "REPUVE", "TRANSUNION 1", "TRANSUNION 2", 
  "VERIFICACION DE FACTURA 1", "VERIFICACION DE FACTURA 2", "CONTRATO DE COMPRA-VENTA", 
  "IMAGEN ESCANER", "IMAGEN VIN", "REPORTE ESCANER"
];`;

code = code.replace(/const DOCS_TODOS = \[\s*[\s\S]*?\];/m, newDocsTodos);

fs.writeFileSync('appscript_v5.js', code);
